export const HK_COLLECTIONS = {
  staffUsers: 'hk_staff_users',
  departments: 'hk_departments',
  staffDepartments: 'hk_staff_departments',
  students: 'hk_students',
  studentProfiles: 'hk_student_profiles',
  applicationPeriods: 'hk_application_periods',
  identityResetRequests: 'hk_identity_reset_requests',
  auditLogs: 'hk_audit_logs',
  periodStudentProfiles: 'hk_period_student_profiles',
  applicationCategories: 'hk_application_categories',
  studentCategoryEntries: 'hk_student_category_entries',
  forms: 'hk_forms',
  formVersions: 'hk_form_versions',
  formSections: 'hk_form_sections',
  formFields: 'hk_form_fields',
  formFieldOptions: 'hk_form_field_options',
  formRules: 'hk_form_rules',
  formSubmissions: 'hk_form_submissions',
  formSubmissionVersions: 'hk_form_submission_versions',
  formAnswers: 'hk_form_answers',
  pdfDocuments: 'hk_pdf_documents',
  applications: 'hk_applications',
  applicationStatusHistory: 'hk_application_status_history',
  applicationReviews: 'hk_application_reviews',
  applicationStaffAssignments: 'hk_application_staff_assignments',
  categoryDepartmentAssignments: 'hk_category_department_assignments',
  supplementRequests: 'hk_supplement_requests',
  fundingDecisions: 'hk_funding_decisions',
  fundingDecisionItems: 'hk_funding_decision_items',
  fundingRules: 'hk_funding_rules',
  attachments: 'hk_attachments',
  signedDocuments: 'hk_signed_documents',
  supplementSubmissions: 'hk_supplement_submissions',
  followUpTaskTemplates: 'hk_follow_up_task_templates',
  categoryFollowUpTemplates: 'hk_category_follow_up_templates',
  followUpTasks: 'hk_follow_up_tasks',
  followUpSubmissions: 'hk_follow_up_submissions',
  followUpReviews: 'hk_follow_up_reviews',
  notificationTemplates: 'hk_notification_templates',
  notifications: 'hk_notifications',
  notificationDeliveries: 'hk_notification_deliveries',
  notificationPreferences: 'hk_notification_preferences',
  reminderRules: 'hk_reminder_rules',
  scheduledNotifications: 'hk_scheduled_notifications',
  serviceAccounts: 'hk_service_accounts',
  categoryRules: 'hk_category_rules',
  livingAllowanceRules: 'hk_living_allowance_rules',
  rewardRules: 'hk_reward_rules',
  rewards: 'hk_rewards',
  disbursementPlans: 'hk_disbursement_plans',
  disbursementMilestones: 'hk_disbursement_milestones',
  disbursements: 'hk_disbursements',
  counselors: 'hk_counselors',
  departmentCounselors: 'hk_department_counselors',
  faqArticles: 'hk_faq_articles',
  academicYearPolicies: 'hk_academic_year_policies',
} as const

/** @deprecated Use HK_COLLECTIONS */
export const COLLECTIONS = HK_COLLECTIONS

export type CollectionName = (typeof HK_COLLECTIONS)[keyof typeof HK_COLLECTIONS]
