export const HAD_COLLECTIONS = {
  staffUsers: 'had_staff_users',
  departments: 'had_departments',
  staffDepartments: 'had_staff_departments',
  students: 'had_students',
  studentProfiles: 'had_student_profiles',
  applicationPeriods: 'had_application_periods',
  identityResetRequests: 'had_identity_reset_requests',
  auditLogs: 'had_audit_logs',
  periodStudentProfiles: 'had_period_student_profiles',
  applicationCategories: 'had_application_categories',
  studentCategoryEntries: 'had_student_category_entries',
  forms: 'had_forms',
  formVersions: 'had_form_versions',
  formSections: 'had_form_sections',
  formFields: 'had_form_fields',
  formFieldOptions: 'had_form_field_options',
  formRules: 'had_form_rules',
  formSubmissions: 'had_form_submissions',
  formSubmissionVersions: 'had_form_submission_versions',
  formAnswers: 'had_form_answers',
  pdfDocuments: 'had_pdf_documents',
  applications: 'had_applications',
  applicationStatusHistory: 'had_application_status_history',
  applicationReviews: 'had_application_reviews',
  applicationStaffAssignments: 'had_application_staff_assignments',
  categoryDepartmentAssignments: 'had_category_department_assignments',
  supplementRequests: 'had_supplement_requests',
  fundingDecisions: 'had_funding_decisions',
  fundingDecisionItems: 'had_funding_decision_items',
  fundingRules: 'had_funding_rules',
  attachments: 'had_attachments',
  signedDocuments: 'had_signed_documents',
  supplementSubmissions: 'had_supplement_submissions',
  followUpTaskTemplates: 'had_follow_up_task_templates',
  categoryFollowUpTemplates: 'had_category_follow_up_templates',
  followUpTasks: 'had_follow_up_tasks',
  followUpSubmissions: 'had_follow_up_submissions',
  followUpReviews: 'had_follow_up_reviews',
  notificationTemplates: 'had_notification_templates',
  notifications: 'had_notifications',
  notificationDeliveries: 'had_notification_deliveries',
  notificationPreferences: 'had_notification_preferences',
  scheduledNotifications: 'had_scheduled_notifications',
} as const

/** @deprecated Use HAD_COLLECTIONS */
export const COLLECTIONS = HAD_COLLECTIONS

export type CollectionName = (typeof HAD_COLLECTIONS)[keyof typeof HAD_COLLECTIONS]
